### ISSUE TITLE
关于固件写入

### ISSUE THREAD

**Issue by liumingxuan0** [radiantwf/esp32-circuitpython-switch-joystick#1]
对于N4R2，请问是将\firmware\lolin-s2-mini下的三个文件夹（hori、switch_pro、tinyuf2-lolin_s2_mini-0.11.0）中的bin文件都写入吗？

**Comment by radiantwf** [comment]
不需要，tinyuf2是固件刷写工具，可以刷写UF2的固件，如果不需要频繁刷写固件可以不用刷写这个固件。
然后 hori与switch_pro 是两个手柄，2选1即可，现在程序是switch_pro手柄的，如果使用hori的固件，需要把[root_Hori](https://github.com/radiantwf/esp32-circuitpython-switch-joystick/tree/main/src/root_Hori) 目录下内容 替换 [src](https://github.com/radiantwf/esp32-circuitpython-switch-joystick/tree/main/src) 同名文件。

两款手柄发送信号方式略有不同，精度可能略有区别，可根据自己需要更改，一开始使用，先用switch_pro的就可以了。

**Comment by liumingxuan0** [comment]
好的，十分感谢
