### ISSUE TITLE
关于如何调试

### ISSUE THREAD

**Issue by nonkr** [radiantwf/esp32-circuitpython-switch-joystick#4]
请教Raspberry Pi Pico的MicroUSB口接到了Switch上之后，如何在运行时打印调试呢？

**Comment by radiantwf** [comment]
连接到switch后，没法直接调试，可以使用其他管脚外接pc进行串口通信。
或直接插入PC调试，可以通过 https://gamepad-tester.com/ 页面，来查看按键操作。
