### ISSUE TITLE
Bluetooth support

### ISSUE THREAD

**Issue by ghost** [radiantwf/esp32-circuitpython-switch-joystick#5]
可以实现通过蓝牙连接的方式替代otg有线连接switch吗

**Comment by radiantwf** [comment]
由于蓝牙在精细控制方向时候并不稳定，所以没做蓝牙的开发。并且由于朱紫游戏优化不好，有吞键问题，现在已经再开始开发视频识别版本，所以暂时没有增加这个程序的蓝牙支持计划。
