### ISSUE TITLE
脚本语法：如何按住某个按键的同时点击另一个按键。

### ISSUE THREAD

**Issue by zhangliuda** [radiantwf/esp32-circuitpython-switch-joystick#6]
作者您好，我查阅了给出的例句，语法规则和内部给出的脚本中好像没有包含可以按住一个按键之后频率点击另一个按键的操作方式。我想要做到如下效果：按住摇杆右走，不松开摇杆的情况下每0.2秒点击一下Y按键。期待您的回答。

**Comment by radiantwf** [comment]
抱歉，之前没看到，现在才看到，是支持个语法的。
例如：
{
	LStick@127,0:0.4->Y|LStick@127,0:0.1->~
} * 9
每行默认有0.1秒的时间间隔。
-> 符号：代表两条语句运行时间没有间隔
->~ 符号：可以取消本行与下一行脚本间的运行时间间隔
